# This file shows the default configurations for all configurable items of blogo.
# Any custom changes should be done in your own file `~/.blogo/config.toml`, which will overwrite the defaults.


[website]
title = "BloGo"
description = "BloGo is a lightweight static blog engine built with Go"
author = "Anonymous"
# since_year = current_year
article_page_size = 10
favicon_path = "~/.blogo/favicon.ico"
logo_path = "~/.blogo/logo.svg"
template_path = "web/template"

[repository]
local_path = "~/.blogo/blog"
# Blog repo remote URL, starting with 'https' and ending with '.git'.
# remote_url = "https://github.com/${username}/${reponame}.git"
branch = "main"

[server]
port = 8080

[mysql]
host = "mysql"
port = 3306
database = "blogo"
username = "root"
password = "xxxxxx"
