-- Create table article if not exists.
CREATE TABLE IF NOT EXISTS article (
	id BIGINT NOT NULL,
	slug VARCHAR(255) NOT NULL,
	title VARCHAR(255) NOT NULL,
	content MEDIUMTEXT NOT NULL,
	preview TEXT NOT NULL,
	categories VARCHAR(64) NOT NULL,
	tags VARCHAR(64) NOT NULL,
	top BOOLEAN DEFAULT FALSE,
	draft BOOLEAN DEFAULT FALSE,
	published_ts DATETIME NOT NULL,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),
	PRIMARY KEY (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;